### ISSUE TITLE
Problem with italic formatting via underscore and underscore in attributes

### ISSUE THREAD

**Issue by Connum** [arve0/markdown-it-attrs#83] opened 2019-05-14 17:03 UTC
There is an issue when a whole link with an attribute containing an underscore is wrapped in bold and italic (or just italic) and the italic formatting is done by an underscore instead of three asterisks.

```md
**_[link](https://github.com){target="_blank"}_**
```

is rendered as `_link{target="blank"}`
```html
<strong>_<a href="https://github.com">link</a>{target="<em>blank"}</em></strong>
```

Expected output:
```html
<em><strong><a href="https://github.com" target="_blank">link</a></strong></em>
```
---
and

```md
_[link](https://github.com){target="_blank"}_
```

is rendered as `_link{target="blank"}`
```html
_<a href="https://github.com">link</a>{target="<em>blank"}</em>
```

Expected output:
```html
<em><a href="https://github.com" target="_blank">link</a></em>
```
---
However, if you switch the bold and italic formatting, it works as supposed to:
```html
_**[link](https://github.com){target="_blank"}**_
```

**Comment by arve0** [comment] 2019-05-14 18:57
I think this is due to the `_` underscore in `_blank`. Have you tried `***[link](https://github.com){target="_blank"}***`?

**Comment by Connum** [comment] 2019-05-14 20:30
Yup, the triple asterisks work, but the environment I'm using markdown-it in requires italics via _ to work as well.

**Comment by arve0** [comment] 2019-05-15 05:20
It's hard to work around the ambiguity of underscores inside and outside attributes. If you want to know why, have a look at the [token tree](https://markdown-it.github.io):

1. insert `_[a link](/url){id=_abc}_`
2. click on debug

To me, fixing this it's a lot of work for little gain. If you find a clever way working around it, let us know 🙂

**Comment by Connum** [comment] 2019-05-15 15:40
I'm still confused why
```**_[link](https://github.com){target="_blank"}_**```
works and swapping bold/italic
```_**[link](https://github.com){target="_blank"}**_```
doesn't. Any idea?

**Comment by arve0** [comment] 2019-06-03 16:10
I'm closing this, as this is expected behavior of markdown-it parser.

**Closed by arve0** 2019-06-03 16:10 UTC
