### ISSUE TITLE
Cannot read property 'attrJoin' of undefined

### ISSUE THREAD

**Issue by hashinteractive** [arve0/markdown-it-attrs#93] opened 2019-07-30 15:55 UTC
If we use an inline markdown with the markdown-it-attrs syntax such as:
`This is a *bold*{.btn} paragraph`

We're getting this error:
```
exports.addAttrs = function (attrs, token) {
  for (let j = 0, l = attrs.length; j < l; ++j) {
    let key = attrs[j][0];
    if (key === 'class') {
      token.attrJoin('class', attrs[j][1]);
    } else if (key === 'css-module') {
      token.attrJoin('css-module', attrs[j][1]);
    } else {
      token.attrPush(attrs[j]);
    }
```
Found in: 
`node_modules/markdown-it-attrs/utils.js`

Looks like it might be related to issue: https://github.com/arve0/markdown-it-attrs/issues/90 as if it's not a `'class'` key then the else statement is executed resulting in the 'Cannot read property 'attrPush' of undefined' error

**Comment by arve0** [comment] 2019-07-30 17:12
Duplicate of #90.

**Closed by arve0** 2019-07-30 17:12 UTC
